---

- name: Setup site table
  command: >-
    /opt/xcat/bin/chdef -t site forwarders={{ site.forwarders }} master={{ site.master }}
    nameservers={{ site.nameservers }} domain={{ site.domain }}
    dhcpinterfaces={{ site.dhcpinterfaces }}
  tags: configsite

- name: Setup password
  shell: |
    /opt/xcat/sbin/chtab key=system passwd.username=root passwd.password=cluster
    /opt/xcat/sbin/chtab key=ipmi passwd.username=USERID passwd.password=PASSW0RD

- name: Prepare hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ site.master }} {{ ansible_hostname }} {{ ansible_hostname }}.{{ site.domain }}"

- name: Make DNS with 'makedns'
  command: /opt/xcat/sbin/makedns -n
  ignore_errors: true

- name: Update default network
  shell: |
    netnames=($(/opt/xcat/bin/lsdef -t network | cut -d ' ' -f 1))
    for netname in ${netnames[@]}
    do
      net=$(/opt/xcat/bin/lsdef -t network $netname -i net | sed '1d' | cut -d '=' -f 2)
      staticrange=$(echo $net | cut -d '.' -f 1-3).3-$(echo $net | cut -d '.' -f 1-3).200
      dynamicrange=$(echo $net | cut -d '.' -f 1-3).201-$(echo $net | cut -d '.' -f 1-3).254
      /opt/xcat/bin/chdef -t network -o $netname staticrange=$staticrange dynamicrange=$dynamicrange
    done
  tags: updatenet

- name: Make DHCP with 'makedhcp'
  command: /opt/xcat/sbin/makedhcp -n
  ignore_errors: true

# - name: Setup conserver
#   command: /opt/xcat/sbin/makeconservercf
#   ignore_errors: true

- name: Ensure dhcpd started
  service: name=dhcpd state=started
  when: ansible_distribution == "RedHat"
